### ISSUE TITLE
Cancellation

### ISSUE THREAD

**Issue by benjamingr** [nodejs/promises#17]
Promise cancellation is currently being discussed - roughly (with minor differences) similar to http://bluebirdjs.com/docs/api/cancellation.html 

This basically lets us cancel requests that are irrelevant.

I'd like to see Node weigh in this time before this is set in stone rather than after.

**Comment by vkurchatkin** [comment]
I think this discussion belongs to ES Discuss, etc, as it's a language level concept. 

Also to be fair I doubt that cancellation will ever be added to promises, since it violates functional purity.

**Comment by benjamingr** [comment]
@vkurchatkin it's very likely that it will and IMO it doesn't.

This discussion in general belongs on ES-Discuss but I want to make sure Node's perspective is represented in these discussions this time. I have a feeling that node core members feel underrepresented in language discussions and we can try to address that by making meaningful contributions to these discussions.

So, I'd like to raise what Node wants for these issues so when the time comes we'll have meaningful contributions to the discussion.

**Comment by vkurchatkin** [comment]
> it's very likely that it will and IMO it doesn't.

What makes you think so? To be honest, I'd be very upset.

**Comment by benjamingr** [comment]
Violate purity or will enter the spec?

Enter the spec - mainly (mostly justified) pressure from the DOM groups to enable cancellation in DOM related APIs. 

Purity - I used to think so for a long time but I honestly cancellation as a third state with disinterest semantics addresses that very nicely. Instead of abortive semantics which cause action at a distance, are confusing and are not sound (this is what we had in the past) they're working on disinterest semantics which means you get consistent behavior.

Bluebird switched the implementation to those semantics - I'd love it if you took a look and gave feedback.

**Comment by spion** [comment]
Promises are already impure, creating a promise starts the IO operation.

Haskell IO actions are pure and only represent values that contain specs for what the runtime should execute. They are basically like thunks (closures with no arguments / only a continuation argument). Giving an IO action to the current runtime chain will execute that spec. Passing it again will execute that spec again.

**Comment by vkurchatkin** [comment]
@benjamingr 

>  cancellation as a third state with disinterest semantics addresses that very nicely

The problem is that currently promises are stateless and free of side effects, at least one of these properties have to be abandoned.

> working on disinterest semantics which means you get consistent behavior.

I agree with this approach, but I'd prefer a different primitive. Say, `Task`. `Promise` represents a value, `Task` represents a process. It makes sense that you can't cancel a value, or observe progress, etc.

I currently work on go-style approach for my company's services, it's basically a SLA-aware cancellation token/map of values (https://godoc.org/golang.org/x/net/context for reference).

**Comment by vkurchatkin** [comment]
> Promises are already impure, creating a promise starts the IO operation.

Promises are pure, but user-provided functions are not necessarily. If underlying framework returns promises, then it's possible to make everything pure. That shouldn't be a goal for js code, though.

**Comment by benjamingr** [comment]
@spion Haskell IO actions are not pure. If they were pure they would not do anything or would have to return the same value each time :D 

You can look at promises the same way - where the host environment is the runtime. You can look at functions that return promises similarly to thunks.

**Comment by benjamingr** [comment]
@vkurchatkin 

> The problem is that currently promises are stateless and free of side effects, at least one of these properties have to be abandoned.

I'm not so sure. Promises are stateless only after they resolve - that does not change. What happens is that a third state is added (cancelled) that has disinterest semantics.

If the underlying source resolved already then disinterest semantics mean the chain only executes `finally` handlers and resource cleanup and neither onFulfilled nor onRejected handlers.

If the underlying source did not resolve yet - the exact same thing happens on the consumer side (finally executes, then and catch don't) but additionally the source gets the signal and the promise is resolved on a third `cancelled` state. 

The important thing is that in disinterest semantics the consumer side behaves the exact same way in either case.

> Promise represents a value, Task represents a process. It makes sense that you can't cancel a value, or observe progress, etc.

I agree, this is why perhaps cancellation is not a great name for it - disinterest is probably better. You can "show disinterest" in a value at which point cancellation is not up to you but to the producer. 

> I currently work on go-style approach for my company's services, it's basically a SLA-aware cancellation token/map of values (https://godoc.org/golang.org/x/net/context for reference).

Cancellation tokens are also an approach being explored.

----

Back to the topic, I'm more interested in knowing what _node_ needs from cancellation semantics.

**Comment by petkaantonov** [comment]
Yes this thread is about integrating cancellation with node when cancellation comes. But last time I checked standardized cancellation hasn't decided whether it uses branch counts like bluebird or cancellation tokens (like #C i presume).

**Comment by spion** [comment]
@benjamingr no, you cannot.

A haskell function that returns IO does the following:

```js
function readFile(path) {
  return function(callback) {
    actuallyReadFile(path, callback);
  }
}
```

The value of the action is

```js
function(callback) {
  actuallyReadFile(path, callback);
}
```

and its a pure value that was created without side effects.

It may seem like bikeshed but it highlights that promises don't provide Haskell-like purity of IO, but only an async DSL of the same impure synchronous JS semantics.

**Comment by petkaantonov** [comment]
>  Say, Task. Promise represents a value, Task represents a process. 

Promises already represent both in ecosystem APIs and web apis.

**Comment by benjamingr** [comment]
> It may seem like bikeshed but it highlights that promises don't provide Haskell-like purity of IO, but only an async DSL of the same impure synchronous JS semantics.

I'm well aware of what thunks are. You can't execute Haskell's I/O functions out of nowhere the runtime has to provide the actual IO for you - like in JavaScript. Impure things have to happen either way because if all code is pure nothing gets executed :D

**Comment by spion** [comment]
@benjamingr regardless, I think its important to stress the difference. All these elements are intertwined and their design is deliberate - its important to put forward the design of promises and its intent if we want to evaluate proposals that change it.

**Comment by vkurchatkin** [comment]
>  Promises are stateless only after they resolve - that does not change

Promises are stateless, because you can't observe or modify state. They are opaque.

> I agree, this is why perhaps cancellation is not a great name for it - disinterest is probably better.

This is implies state mutation, though.

> Promises already represent both in node ecosystem APIs and standard Web APIs.

What web APIs? `fetch`? it was a mistake, obviously.

**Comment by petkaantonov** [comment]
From the top of my head: `event.waitUntil()`, `audioContext.resume()`, `audioContext.suspend()`

**Comment by kriskowal** [comment]
To be clear, purity is not a concern, but plan interference hazards are.
Passing a promise to multiple consumers, one consumer should not be able to
interfere with the progress of the other consumer. That is the inviolable
constraint. It seems likely that, using promises, this problem should be
solved by passing a promise to cancel (a cancellation token) as an argument
to any function that requires this two-way communication channel.

**Comment by petkaantonov** [comment]
@kriskowal it should be solved by keeping track of consumer branch counts and only actually aborting the promise when all consumer branches have cancelled. A single consumer branch cancelling only has the guaranteed effect that their fulfillment/rejection handlers are not called. 

I don't actually see how token avoids this, you would have to distribute the token to all consumer branches as well and track that everyone has agreed to cancel the token before aborting the task.

**Comment by kriskowal** [comment]
@petkaantonov The sticking point for the reference counting approach is that you have to give each consumer a unique promise. So if you have a memoized promise-returning function, it needs to call `return memoizedPromise.then()` with no arguments to up the ref-count on the memoized promise. I find this acceptable, but it does violate the principle of least surprise.

**Comment by saschanaz** [comment]
What does the silent closing mean?

**Comment by benjamingr** [comment]
Promise cancellation is no longer discussed in tc39, and the issue has been inactive for a while

**Comment by ljharb** [comment]
@benjamingr that's not entirely accurate; see "Updates on Cancellation Proposals" on [this week's meeting agenda](https://github.com/tc39/agendas/blob/master/2017/05.md)
