### ISSUE TITLE
Patterns directory

### ISSUE THREAD

**Issue by benjamingr** [nodejs/promises#19]
I've started work at https://github.com/nodejs/promises/tree/promise-patterns/patterns describing common promise related patterns so they can be clearly discussed in issues. PR here: https://github.com/nodejs/promises/pull/18

I'd love suggestions and patterns you think should be included here.

**Comment by thefourtheye** [comment]
http://taoofcode.net/promise-anti-patterns/ I found this recently and I think it will be useful

**Comment by vramana** [comment]
http://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html  I think this is excellent in explaining Promise Gotchas
