### ISSUE TITLE
Examples of synchronous operational errors

### ISSUE THREAD

**Issue by benjamingr** [nodejs/promises#23]
I'd like to collect some examples of [operational errors](https://github.com/nodejs/promises/blob/master/GLOSSARY.md#operational-error) in Node that are synchronously thrown at the moment.

**Please post examples you're aware of**

Examples: 
1. Out of memory 
2. Parsing invalid JSON
3. Attempting to bind to a closed UDP socket.
4. Listening to an invalid port

---
### Out of memory

``` js
const arr = []; // example and case by trevnorris
  while (true)
    arr.push(new Buffer(0xfffffff).fill(0));  // alloc until OOM, throws synchronously
```
### Parsing Invalid JSON

``` js
var j = JSON.parse("{'hello': 5}"); // throws synchronously
```
### Attempting to bind to a closed UDP socket

From https://nodejs.org/api/dgram.html

> If binding fails, an 'error' event is generated. In rare case (e.g. attempting to bind with a closed socket), an Error may be thrown.
### Listening to an invalid port

https://github.com/nodejs/node/blob/master/lib/net.js#L1340

---

Of course, every single `*Sync` method in the API throws synchronously, although in theory they could take callbacks and execute them with `err` synchronously. This includes calls to `require` for example.

**Comment by benjamingr** [comment]
Related discussion: https://github.com/nodejs/promises/issues/10

**Comment by petkaantonov** [comment]
I'd generalize that almost any error thrown in core can be operational depending on context. So just search for `throw` and there you go.

**Comment by benjamingr** [comment]
@petkaantonov care to share some examples?

**Comment by thefourtheye** [comment]
I found few such instances while working on https://github.com/nodejs/node/pull/5251. I had to fix the tests as well because they were expecting errors synchronously.
