### ISSUE TITLE
What’s the status of Promises in the core?

### ISSUE THREAD

**Issue by iamakulov** [nodejs/promises#27]
Looks like the latest activity in the repository was in the end of February. What’s the status of Promises in the core? Is there any work going anywhere?

**Comment by vkurchatkin** [comment]
There are two active PRs:
  
 - https://github.com/nodejs/node/pull/6439;
 - https://github.com/nodejs/node/pull/6375;

The second one is too controversial, so it's unlikely to be merged any time soon. Everything else (e.g. returning promises) is pretty much stalled.

**Comment by iamakulov** [comment]
Thank you!
