### ISSUE TITLE
Provide Status Update

### ISSUE THREAD

**Issue by xjamundx** [nodejs/promises#29]
In the readme it suggests following the tags such as `blocks-landing-pr` to see the status of the proposal. In that case, there's really only one issue remaining and it seems to have been open for some time without recent discussion:
https://github.com/nodejs/promises/labels/blocks-landing-pr

Are there other blocking issues? What's needed to move this along?

**Comment by thefourtheye** [comment]
cc @chrisdickinson

**Comment by benjamingr** [comment]
The PR is mostly abandoned as far as I know :/

**Comment by xjamundx** [comment]
When the `async`/`await` stuff lands in node (soonish, per  https://github.com/nodejs/CTC/issues/7#issuecomment-229588116) I imagine there will be a lot of interest in promises in core!

**Comment by thefourtheye** [comment]
@chrisdickinson Unassigned himself from that PR 😞

**Comment by benjamingr** [comment]
@xjamundx  I 100% agree.
