### ISSUE TITLE
`util.toCallback(asyncFn)` - interop of async functions with callbacks.

### ISSUE THREAD

**Issue by benjamingr** [nodejs/promises#6]
Similar to https://github.com/nodejs/promises/issues/5 I'm looking at ways to make the lives of callback users easier with `async/await` landing. I'm wondering if core should provide a method called `toCallback` that takes an async function and converts it to a callback returning function. This is similar to [`asCallback`](http://bluebirdjs.com/docs/api/ascallback.html) except taking a function: 

``` js
async function fooP() {
    // some async/await stuff
    // ...
    return "Hello"; 
}
const foo = util.toCallback(fooP);

foo((err, data) => console.log(data)); // hello
```

The name and where it is are both debatable.

**Comment by chrisdickinson** [comment]
Does anyone object to making this issue non-blocking for the Promises PR?

**Comment by benjamingr** [comment]
This issue is orthogonal (and certainly non-blocking) for the promises-in-core PR. It is only about async functions being more ergonomic to callback users.

**Comment by chrisdickinson** [comment]
Excellent! Did you see [callbackify](https://github.com/chrisdickinson/node-1/blob/promises/lib/internal/callbackify.js) in the existing PR?

**Comment by chrisdickinson** [comment]
Would you object to discussing a public `util.promisify` in this issue, or would you prefer to keep that separate?

**Comment by benjamingr** [comment]
Well, there are different stakeholders so I'd rather keep them separate. It seems like a generally good idea to keep discussions small to include participation. I don't feel very strongly about it though.

**Comment by benjamingr** [comment]
This landed
